name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Build Docker Image
        run: docker build -t react-app .

      - name: Success
        run: echo "CI/CD Pipeline Executed Successfully"